# Generated by Django 2.2.7 on 2019-11-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dinosaur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=105)),
                ('price', models.PositiveIntegerField()),
                ('rarity', models.CharField(choices=[('common', 'common'), ('uncommon', 'uncommon'), ('rare', 'rare'), ('exotic', 'exotic'), ('legendary', 'legendary')], max_length=105)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
